[package]
name = "alda"
description = "Small utility to deal with an ocean of torrents"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Andriy Kushnir (Orhideous) <me@orhideous.name>"]

[dependencies]
clap = "3.0.0-beta.5"
enum-utils = "0.1.2"
